# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_rigthmenu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RigthMenu',
            new_name='RightMenu',
        ),
    ]
