# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_auto_20180717_1228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RightMenu',
        ),
    ]
