# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_auto_20180729_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leftmenu',
            options={'permissions': (('ver_item_menu', 'Ver item menu'),), 'verbose_name': 'Item de menu', 'verbose_name_plural': 'Items de menu'},
        ),
    ]
