# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-29 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_auto_20180801_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='second_name',
        ),
        migrations.AddField(
            model_name='student',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name=b'Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name=b'Nombre'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=1, null=True, verbose_name=b'Genero'),
        ),
        migrations.AlterField(
            model_name='student',
            name='identifier',
            field=models.CharField(max_length=64, verbose_name=b'DNI'),
        ),
    ]
