# Generated by Django 2.1 on 2018-10-05 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0011_auto_20180729_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=64, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=64, verbose_name='Apellido')),
                ('identifier', models.CharField(max_length=64, verbose_name='DNI')),
                ('gender', models.CharField(max_length=1, null=True, verbose_name='Genero')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('user', models.OneToOneField(null=True, on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_birthday', 'Ver cumpleaños'),),
                'verbose_name_plural': 'Personas',
                'verbose_name': 'Persona',
            },
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_responsible', models.BooleanField(default=False, verbose_name='Es responsable legal')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Fecha inicio vigencia')),
                ('end_date', models.DateField(null=True, verbose_name='Fecha fin vigencia')),
            ],
            options={
                'verbose_name_plural': 'Relacion responsables alumno',
                'verbose_name': 'Relacion responsable alumno',
            },
        ),
        migrations.CreateModel(
            name='ResponsiblePerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('has_perm', models.BooleanField(default=True, verbose_name='Tiene permiso')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.Responsible', verbose_name='Responsable')),
            ],
            options={
                'verbose_name_plural': 'Permisos responsables',
                'verbose_name': 'Permiso responsable',
            },
        ),
        migrations.CreateModel(
            name='ResponsiblePermType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Permiso')),
                ('description', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('perms', django_mysql.models.JSONField(default=None)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Permisos responsables',
                'verbose_name': 'Tipo de Permiso responsable',
            },
        ),
        migrations.CreateModel(
            name='ResponsibleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Relacion')),
                ('description', models.CharField(max_length=255, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name_plural': 'Tipos de responsables',
                'verbose_name': 'Tipo de responsable',
            },
        ),
        migrations.RemoveField(
            model_name='studenttutor',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studenttutor',
            name='tutor',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('view_birthday', 'Ver cumpleaños'),), 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leftmenu',
            name='codename',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='leftmenu',
            name='perm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='Permission'),
        ),
        migrations.AlterField(
            model_name='leftmenu',
            name='text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='leftmenu',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=1, null=True, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='student',
            name='identifier',
            field=models.CharField(max_length=64, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Apellido'),
        ),
        migrations.DeleteModel(
            name='StudentTutor',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
        migrations.AddField(
            model_name='responsible',
            name='relationship',
            field=models.ForeignKey(on_delete=None, to='security.ResponsibleType', verbose_name='Relacion'),
        ),
        migrations.AddField(
            model_name='responsible',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to='security.Person', verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='responsible',
            name='student',
            field=models.ForeignKey(on_delete=None, related_name='student', to='security.Person', verbose_name='Alumno'),
        ),
    ]
