# Generated by Django 2.1 on 2018-11-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0012_auto_20181005_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('view_birthday', 'Ver cumpleaños'), ('config_preferencies', 'Configurar preferencias'), ('config_users', 'Configurar usuarios'), ('config_instance', 'Configurar instancia'), ('config_records', 'Configurar registros de datos')), 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
    ]
