# Generated by Django 2.1 on 2018-11-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0013_auto_20181121_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('view_birthday', 'Ver cumpleaños'), ('view_profile', 'Ver perfil'), ('config_preferencies', 'Configurar preferencias'), ('config_users', 'Configurar usuarios'), ('config_instance', 'Configurar instancia'), ('config_records', 'Configurar registros de datos')), 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
    ]
