# Generated by Django 2.1 on 2019-01-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0015_auto_20181212_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifierType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Relacion')),
                ('description', models.CharField(max_length=255, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documentos',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='identifier_type',
            field=models.ForeignKey(default=1, on_delete=None, to='security.IdentifierType', verbose_name='Tipo Documento'),
        ),
    ]
