from security.models.Student import Student
from security.models.UserProfile import UserProfile
from security.models.Person import Person
from security.models.LeftMenu import LeftMenu
from security.models.Responsible import Responsible
from security.models.ResponsiblePerm import ResponsiblePerm
from security.models.ResponsiblePermType import ResponsiblePermType
from security.models.ResponsibleType import ResponsibleType
from security.models.IdentifierType import IdentifierType
